API_VERSION = '0.1'
SERVER_PEPPER = 'changeme'
SERVER_DEFAULT_ADMIN_PASSWORD = 'Change_Me'

POSTGRES_HOST = 'db'
POSTGRES_USER = 'postgres'
POSTGRES_PASS = 'changeme'

ROLE_USER = 'user'
ROLE_USER_ADMIN = 'user_admin'
ROLE_SUPER = 'super'
ALL_ROLES = [ROLE_USER, ROLE_USER_ADMIN, ROLE_SUPER]

JWT_SECRET = 'changeme'
JWT_ALGORITHM = 'HS512'
JWT_TTE = 60 * 30
JWT_HEADER = 'X-API-Key'
